Repository chickengak/walness, pull requests merged in 2024-04, with the labels that each got.

#4 edit index.html
  mysite/polls/templates/index.html
Labels: enhancement

#8 edit html files
  mysite/polls/templates/index.html
  mysite/polls/templates/left-sidebar.html
  mysite/polls/templates/no-sidebar.html
  mysite/polls/templates/right-sidebar.html
Labels: enhancement

#12 add floating ad
  mysite/polls/templates/index.html
Labels: enhancement

#15 add image
  mysite/static/images/about-img.jpg
  mysite/static/images/contact-img.jpg
  mysite/static/images/dog1.jpg
  mysite/static/images/dots.png
  mysite/static/images/happydog.jpg
  mysite/static/images/logo.png
  mysite/static/images/next.png
  mysite/static/images/post1.jpg
  mysite/static/images/post2.jpg
  mysite/static/images/post3.jpg
  mysite/static/images/post4.png
  mysite/static/images/prev.png
  mysite/static/images/slider-img.jpg
  mysite/static/images/t1.png
  mysite/static/images/t2.png
  mysite/static/images/t3.png
  mysite/static/images/t4.png
  mysite/static/images/team1.jpg
  mysite/static/images/team2.jpg
  mysite/static/images/team3.jpg
  mysite/static/images/treatment-side-img.jpg
Labels: enhancement

#16 Adjust google map
  mysite/polls/templates/no-sidebar.html
Labels: enhancement

#22 change ad image
  mysite/polls/templates/index.html
  mysite/static/images/ad01.jpg
Labels: enhancement

#24 Manage api using json
  .gitignore
  mysite/keys.json
  mysite/mysite/settings.py
  mysite/polls/templates/no-sidebar.html
  mysite/polls/views.py
Labels: enhancement

#26 Add Images on service explanation part
  mysite/keys.json
  mysite/polls/templates/index.html
  mysite/static/css/main.css
  mysite/static/images/walness_cam.png
Labels: enhancement

#28 add ad02
  mysite/polls/templates/left-sidebar.html
  mysite/static/images/ad02.jpg
Labels: enhancement

#32 Load animal hospital's info
  mysite/polls/views.py
  mysite/temp.json
Labels: enhancement

#33 Update About Wellness part
  mysite/polls/templates/index.html
Labels: enhancement

#37 index,left_sidebar
  mysite/polls/templates/index.html
  mysite/polls/templates/left-sidebar.html
  mysite/polls/templates/no-sidebar.html
  mysite/polls/templates/right-sidebar.html
Labels: enhancement

#39 Update About Walness part
  mysite/polls/templates/index.html
Labels: enhancement

#41 index correction
  mysite/polls/templates/index.html
  mysite/polls/templates/left-sidebar.html
  mysite/polls/templates/no-sidebar.html
Labels: enhancement

#43 Issue#42 bug fix
  mysite/keys.json
  mysite/mysite/settings.py
Labels: bug

#45 Update Image uploading part
  mysite/polls/templates/index.html
  mysite/static/css/main.css
Labels: enhancement

#48 Issue#46
  mysite/polls/templates/no-sidebar.html
  mysite/static/js/mapp.js
Labels: enhancement

#50 Modify google map
  mysite/polls/templates/no-sidebar.html
  mysite/static/css/index.css
  mysite/static/js/mapp.js
Labels: enhancement

#52 sort by distance
  mysite/static/js/mapp.js
Labels: enhancement

#54 Add Image upload feature
  mysite/polls/templates/index.html
  mysite/static/css/main.css
Labels: enhancement

#56 Add searching by rating
  mysite/polls/templates/no-sidebar.html
  mysite/static/js/mapp.js
Labels: enhancement

#58 Add maker of curLocation And modify li.addEventListener
  mysite/static/css/index.css
  mysite/static/js/mapp.js
Labels: enhancement

#60 add selected item name popup
  mysite/static/js/mapp.js
Labels: enhancement

#62 image imput
  mysite/polls/templates/index.html
  mysite/polls/templates/left-sidebar.html
Labels: enhancement

#66 Fix sidebar sorting
  mysite/static/js/mapp.js
Labels: bug, enhancement

#68 Issue#67
  mysite/static/js/mapp.js
Labels: enhancement

#71 Fixed the problem of not being able to append sorted hospitals and cu…
  mysite/polls/templates/no-sidebar.html
  mysite/static/css/index.css
  mysite/static/js/mapp.js
Labels: bug, enhancement

#73 Using the attached image, upload and then load it
  .gitignore
  mysite/mysite/settings.py
  mysite/polls/forms.py
  mysite/polls/migrations/0001_initial.py
  mysite/polls/models.py
  mysite/polls/templates/index.html
  mysite/polls/templates/no-sidebar.html
  mysite/polls/urls.py
  mysite/polls/views.py
  mysite/static/css/main.css
  requirements.txt
Labels: enhancement

#77 completed prediction function
  mysite/polls/utils.py
Labels: enhancement

#79 Modify style of results
  mysite/polls/templates/index.html
  mysite/static/css/main.css
Labels: enhancement

#81 Modify labels
  mysite/polls/templates/index.html
  mysite/polls/utils.py
Labels: enhancement

#83 make banner ad and modify accuracy format
  mysite/polls/templates/index.html
  mysite/polls/utils.py
  mysite/static/images/ad01_banner.jpg
Labels: enhancement

#85 Add button on result part
  mysite/polls/templates/index.html
  mysite/static/css/main.css
Labels: enhancement

#89 gradcam
  mysite/polls/utils.py
  mysite/polls/views.py
Labels: enhancement

#93 model.h5 add
  mysite/polls/utils.py
Labels: enhancement

#95 add dog/cat selection
  mysite/polls/templates/index.html
  mysite/polls/templates/no-sidebar.html
  mysite/polls/utils.py
  mysite/polls/views.py
Labels: enhancement

#98 gradcam modify
  mysite/polls/utils.py
Labels: enhancement

#100 fix button position
  mysite/polls/templates/index.html
Labels: enhancement

#102 add info
  mysite/polls/templates/index.html
  mysite/polls/templates/left-sidebar.html
  mysite/polls/templates/no-sidebar.html
Labels: enhancement
